change naming from mlsql to byzer
byzer-org/byzer-k8s pull request #4
Opened 2022-04-06 12:41 UTC by ZhengshuaiPENG

2022-04-07 00:55 UTC, allwefantasy requested changes

2022-04-07 00:55 UTC, allwefantasy commented on README.md
> +  --engine-image byzer/byzer-lang-k8s:3.1.1-latest \
这里镜像名字也同步了吧？

2022-04-07 01:45 UTC, allwefantasy requested changes

2022-04-07 01:45 UTC, allwefantasy commented on README.md
> +  --engine-access-token byzer   \
同理 配置在镜像里的 application.yml 文件 1) 是否做了配置 2) 是否名字也做了修改

2022-04-07 07:06 UTC, ZhengshuaiPENG commented on README.md
> +  --engine-image byzer/byzer-lang-k8s:3.1.1-latest \
目前镜像的tag就是叫这个名字

2022-04-07 07:23 UTC, ZhengshuaiPENG commented on README.md
> +  --engine-access-token byzer   \
镜像里目前不存在 application.yml 文件

2022-04-14 01:24 UTC, allwefantasy approved these changes

2022-04-14 01:24 UTC, merged